import { defineConfig, devices } from '@playwright/test'
import { isolateTestCredentials } from './scripts/test-environment.mjs'

isolateTestCredentials()

export default defineConfig({
  testDir: './tests/e2e',
  fullyParallel: false,
  workers: 5,
  timeout: 30000,
  expect: { timeout: 7000 },
  reporter: [['list'], ['html', { open: 'never' }]],
  use: { trace: 'retain-on-failure', screenshot: 'only-on-failure', ...devices['Desktop Chrome'] },
  projects: [
    { name: 'journeys-github-projects', testMatch: 'github-projects.spec.ts' },
    { name: 'layout-webkit-github-projects', testMatch: 'github-projects.spec.ts', use: { browserName: 'webkit', isMobile: true, hasTouch: true } },
    { name: 'journeys-claude', testMatch: 'claude.spec.ts' },
    { name: 'layout-webkit-claude', testMatch: 'claude.spec.ts', use: { browserName: 'webkit', isMobile: true, hasTouch: true } },
    { name: 'journeys-onepassword', testMatch: 'onepassword.spec.ts' },
    { name: 'layout-webkit-onepassword', testMatch: 'onepassword.spec.ts', use: { browserName: 'webkit', isMobile: true, hasTouch: true } },
    { name: 'journeys-live', testMatch: 'live.spec.ts' },
    { name: 'layout-webkit-live', testMatch: 'live.spec.ts', use: { browserName: 'webkit' } },
    { name: 'journeys-deliverables', testMatch: 'deliverables.spec.ts' },
    { name: 'layout-webkit-deliverables', testMatch: 'deliverables.spec.ts', use: { browserName: 'webkit', hasTouch: true } },
    { name: 'layout-ui-review', testMatch: 'ui-review.spec.ts' },
    { name: 'layout-webkit-resources', testMatch: 'ui-review.spec.ts', grep: /keeps projects/, use: { browserName: 'webkit' } },
    { name: 'journeys-models', testMatch: 'models.spec.ts' },
    { name: 'layout-webkit-models', testMatch: 'models.spec.ts', use: { browserName: 'webkit', hasTouch: true } },
    { name: 'journeys-signal', testMatch: 'signal.spec.ts' },
    { name: 'layout-webkit-signal', testMatch: 'signal.spec.ts', use: { browserName: 'webkit', hasTouch: true } },
    { name: 'journeys-chats', testMatch: 'chats.spec.ts' },
    { name: 'journeys-chat-attachments', testMatch: 'chat-attachments.spec.ts' },
    { name: 'layout-webkit-chat-attachments', testMatch: 'chat-attachments.spec.ts', use: { browserName: 'webkit', hasTouch: true } },
    { name: 'layout-webkit-chats', testMatch: 'chats.spec.ts', use: { browserName: 'webkit', hasTouch: true } },
    { name: 'layout-chromium-scrolling', testMatch: 'scrolling.spec.ts' },
    { name: 'layout-webkit-scrolling', testMatch: 'scrolling.spec.ts', use: { browserName: 'webkit' } },
    { name: 'journeys', testMatch: 'workspace.spec.ts', grepInvert: /appearance follows|dark appearance settings/ },
    { name: 'journeys-appearance', testMatch: 'workspace.spec.ts', grep: /appearance follows|dark appearance settings/ },
    { name: 'journeys-accounts', testMatch: 'accounts.spec.ts' },
    { name: 'layout-webkit-accounts', testMatch: 'accounts.spec.ts', use: { browserName: 'webkit', isMobile: true, hasTouch: true } },
    { name: 'journeys-mcps', testMatch: 'mcps.spec.ts' },
    { name: 'layout-webkit-mcps', testMatch: 'mcps.spec.ts', use: { browserName: 'webkit', isMobile: true, hasTouch: true } },
    { name: 'journeys-task-focus', testMatch: 'task-focus.spec.ts' },
    { name: 'layout-webkit-task-focus', testMatch: 'task-focus.spec.ts', use: { browserName: 'webkit' } },
    { name: 'journeys-agent-access', testMatch: 'agent-access.spec.ts' },
    { name: 'journeys-skill-mentions', testMatch: 'skill-mentions.spec.ts' },
    { name: 'layout-webkit-skill-mentions', testMatch: 'skill-mentions.spec.ts', use: { browserName: 'webkit', hasTouch: true } },
    ...(['chromium', 'webkit'] as const).flatMap(browserName =>
      (['light', 'dark'] as const).map(colorScheme => ({
        name: `layout-${browserName}-${colorScheme}`,
        testMatch: 'layouts.spec.ts',
        use: { browserName, colorScheme, ...(browserName === 'webkit' && colorScheme === 'light' ? { isMobile: true, hasTouch: true, viewport: { width: 390, height: 664 } } : {}) },
      }))),
  ],
})
