import { expect, test } from './fixtures'

test('agent access editor and task inheritance work on mobile in both themes', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByLabel('Password', { exact: true }).fill('browser-password-long-enough')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.locator('.shell')).toBeVisible()
  await page.goto('/agents')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('heading', { name: 'Main agent', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'New agent', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Name', { exact: true }).fill('Scoped reviewer')
  await dialog.getByLabel('All projects, including future projects').uncheck()
  await dialog.getByLabel('Design system', { exact: true }).check()
  await dialog.getByLabel('All available skills').uncheck()
  await dialog.getByLabel('review', { exact: true }).check()
  await expect(dialog.getByLabel('Shared GitHub connection')).not.toBeChecked()
  await expect(dialog.getByLabel('Shared GitHub connection')).toBeDisabled()
  const mode = dialog.getByRole('combobox', { name: 'Execution mode', exact: true })
  await mode.click()
  await page.getByRole('option', { name: 'Read only', exact: true }).click()
  for (const colorScheme of ['light', 'dark'] as const) {
    await page.emulateMedia({ colorScheme })
    await dialog.locator('.agent-access-panel').scrollIntoViewIfNeeded()
    await page.screenshot({ path: testInfo.outputPath(`agent-access-${colorScheme}.png`), animations: 'disabled' })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await dialog.getByRole('button', { name: 'Save agent', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('link', { name: 'Tasks', exact: true }).click()
  await page.getByRole('button', { name: 'New task', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Agent', exact: true })).toHaveValue('Main agent')
  await expect(page.getByRole('combobox', { name: 'Project context', exact: true })).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Agent', exact: true }).click()
  await page.getByRole('option', { name: 'Scoped reviewer', exact: true }).click()
  await page.getByLabel('Task name', { exact: true }).fill('Review the repository')
  await page.getByLabel('What should happen?').fill('Review code without making changes.')
  await expect(page.locator('.agent-scope-summary')).toContainText('1 allowed project')
  await page.screenshot({ path: testInfo.outputPath('agent-first-task.png'), animations: 'disabled' })
  await page.getByRole('button', { name: 'Create task', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Review the repository' })).toBeVisible()
})
