import { expect, expectSingleScroll, test } from './fixtures'

test('Claude sign-in, provider selection and resumed chats work on desktop and mobile', async ({ page, workspace }, testInfo) => {
  test.setTimeout(120000)
  await page.goto('/connections')
  await page.getByLabel('Password', { exact: true }).fill('browser-password-long-enough')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  const section = page.getByRole('region', { name: 'Claude Code', exact: true })
  await section.getByRole('button', { name: 'Connect Claude Code', exact: true }).click()
  await expect(section.getByRole('link', { name: 'Open Claude sign-in' })).toHaveAttribute('href', 'https://claude.com/oauth/authorize?fixture=1')
  await page.reload()
  await expect(section.getByLabel('Claude authorization code')).toBeVisible()
  for (const width of [1440, 390, 320]) {
    await page.setViewportSize({ width, height: 900 })
    await page.emulateMedia({ colorScheme: width === 1440 ? 'light' : 'dark' })
    await expectSingleScroll(page)
    await section.screenshot({ path: testInfo.outputPath(`claude-login-${width}.png`) })
  }
  await section.getByLabel('Claude authorization code').fill('wrong')
  await section.getByRole('button', { name: 'Finish sign-in' }).click()
  await expect(section.getByRole('alert')).toContainText('could not finish')
  await section.getByRole('button', { name: 'Connect Claude Code', exact: true }).click()
  await section.getByLabel('Claude authorization code').fill('fixture-code')
  await section.getByRole('button', { name: 'Finish sign-in' }).click()
  await expect(section.getByText('Connected', { exact: true })).toBeVisible()
  await expect(section).not.toContainText('never-return-this-secret')
  await page.goto('/agents')
  await page.getByRole('button', { name: 'New agent', exact: true }).click()
  await page.getByLabel('Name', { exact: true }).fill('Claude engineer')
  await page.getByRole('combobox', { name: 'Coding agent', exact: true }).click()
  await page.getByRole('option', { name: 'Claude Code', exact: true }).click()
  await page.getByRole('combobox', { name: 'Model', exact: true }).click()
  await page.getByRole('option', { name: 'Sonnet', exact: true }).click()
  await page.getByRole('button', { name: 'Save agent', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const agent = (await workspace.api('/api/agents')).find((a: { name: string }) => a.name === 'Claude engineer')
  expect(agent.provider).toBe('claude')
  const chat = await workspace.api('/api/chats', 'POST', { agentId: agent.id })
  await workspace.api(`/api/chats/${chat.id}/messages`, 'POST', { id: crypto.randomUUID(), text: 'Inspect this workspace' })
  await expect.poll(async () => (await workspace.api(`/api/chats/${chat.id}`)).run?.status, { timeout: 20000 }).toBe('succeeded')
  const first = await workspace.api(`/api/chats/${chat.id}`)
  expect(first.run.summary).toContain('Claude fixture completed')
  await workspace.api(`/api/chats/${chat.id}/messages`, 'POST', { id: crypto.randomUUID(), text: 'Continue reviewing' })
  await expect.poll(async () => (await workspace.api(`/api/chats/${chat.id}`)).run?.resumeCount, { timeout: 20000 }).toBeGreaterThan(0)
  await expect.poll(async () => (await workspace.api(`/api/chats/${chat.id}`)).run?.status).toBe('succeeded')
  await page.goto(`/chats/${chat.id}`)
  await expect(page.getByText('Claude fixture completed', { exact: true })).toHaveCount(2)
  await expectSingleScroll(page)
  await page.screenshot({ path: testInfo.outputPath('claude-chat-mobile.png') })
  await workspace.api(`/api/chats/${chat.id}/messages`, 'POST', { id: crypto.randomUUID(), text: 'fixture:question' })
  await expect.poll(async () => (await workspace.api(`/api/chats/${chat.id}`)).questions?.filter((q: { status: string }) => q.status === 'pending').length, { timeout: 20000 }).toBe(1)
  const question = (await workspace.api(`/api/chats/${chat.id}`)).questions.find((q: { status: string }) => q.status === 'pending')
  await workspace.api(`/api/chats/${chat.id}/questions/${question.id}/answer`, 'POST', { id: crypto.randomUUID(), answers: { 0: ['Small change'] } })
  await expect.poll(async () => (await workspace.api(`/api/chats/${chat.id}`)).run?.status, { timeout: 20000 }).toBe('succeeded')
  const task = await workspace.api('/api/tasks', 'POST', { name: 'Claude scheduled work', prompt: 'Review the workspace', agentId: agent.id })
  const run = await workspace.api(`/api/tasks/${task.id}/run`, 'POST')
  await expect.poll(async () => (await workspace.api(`/api/runs/${run.id}`)).status, { timeout: 20000 }).toBe('succeeded')
  await page.goto('/connections')
  await section.getByRole('button', { name: 'Reconnect', exact: true }).click()
  await section.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(section.getByLabel('Claude authorization code')).toHaveCount(0)
})
