import { expect, expectSingleScroll, test } from './fixtures'

test('Claude sign-in, provider selection and resumed chats work on desktop and mobile', async ({ page, workspace }, testInfo) => {
  test.setTimeout(120000)
  await page.goto('/connections')
  await page.getByLabel('Password', { exact: true }).fill('browser-password-long-enough')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  const section = page.getByRole('region', { name: 'Claude Code', exact: true })
  await section.getByRole('button', { name: 'Connect Claude Code', exact: true }).click()
  await expect(section.getByRole('link', { name: 'Open Claude sign-in' })).toHaveAttribute('href', 'https://claude.com/oauth/authorize?fixture=1')
  await page.reload()
  await expect(section.getByLabel('Claude authorization code')).toBeVisible()
  for (const width of [1440, 390, 320]) {
    await page.setViewportSize({ width, height: 900 })
    await page.emulateMedia({ colorScheme: width === 1440 ? 'light' : 'dark' })
    await expectSingleScroll(page)
    await section.screenshot({ path: testInfo.outputPath(`claude-login-${width}.png`) })
  }
  await section.getByLabel('Claude authorization code').fill('wrong')
  await section.getByRole('button', { name: 'Finish sign-in' }).click()
  await expect(section.getByRole('alert')).toContainText('could not finish')
  await section.getByRole('button', { name: 'Connect Claude Code', exact: true }).click()
  await section.getByLabel('Claude authorization code').fill('fixture-code')
  await section.getByRole('button', { name: 'Finish sign-in' }).click()
  await expect(section.getByText('Connected', { exact: true })).toBeVisible()
  await expect(section).not.toContainText('never-return-this-secret')
  await page.goto('/agents')
  await page.getByRole('button', { name: 'New agent', exact: true }).click()
  await page.getByLabel('Name', { exact: true }).fill('Claude engineer')
  await page.getByRole('button', { name: /^Agent, model and reasoning/ }).click()
  const agentMenu = page.getByRole('dialog', { name: 'Agent & model' })
  await agentMenu.getByRole('radio', { name: 'Claude Code', exact: true }).click()
  await agentMenu.getByRole('radio', { name: 'Sonnet', exact: true }).click()
  await agentMenu.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(page.getByRole('button', { name: /^Agent, model and reasoning: Claude Code · Sonnet/ })).toBeVisible()
  await page.getByRole('button', { name: 'Save agent', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const agent = (await workspace.api('/api/agents')).find((a: { name: string }) => a.name === 'Claude engineer')
  expect(agent.provider).toBe('claude')
  const chat = await workspace.api('/api/chats', 'POST', { agentId: agent.id })
  await workspace.api(`/api/chats/${chat.id}/messages`, 'POST', { id: crypto.randomUUID(), text: 'Inspect this workspace' })
  await expect.poll(async () => (await workspace.api(`/api/chats/${chat.id}`)).run?.status, { timeout: 20000 }).toBe('succeeded')
  const first = await workspace.api(`/api/chats/${chat.id}`)
  expect(first.run.summary).toContain('Claude fixture completed')
  await workspace.api(`/api/chats/${chat.id}/messages`, 'POST', { id: crypto.randomUUID(), text: 'Continue reviewing' })
  await expect.poll(async () => (await workspace.api(`/api/chats/${chat.id}`)).run?.resumeCount, { timeout: 20000 }).toBeGreaterThan(0)
  await expect.poll(async () => (await workspace.api(`/api/chats/${chat.id}`)).run?.status).toBe('succeeded')
  await page.goto(`/chats/${chat.id}`)
  await expect(page.getByText('Claude fixture completed', { exact: true })).toHaveCount(2)
  await expectSingleScroll(page)
  await page.screenshot({ path: testInfo.outputPath('claude-chat-mobile.png') })
  await workspace.api(`/api/chats/${chat.id}/messages`, 'POST', { id: crypto.randomUUID(), text: 'fixture:question' })
  await expect.poll(async () => (await workspace.api(`/api/chats/${chat.id}`)).questions?.filter((q: { status: string }) => q.status === 'pending').length, { timeout: 20000 }).toBe(1)
  const question = (await workspace.api(`/api/chats/${chat.id}`)).questions.find((q: { status: string }) => q.status === 'pending')
  await workspace.api(`/api/chats/${chat.id}/questions/${question.id}/answer`, 'POST', { id: crypto.randomUUID(), answers: { 0: ['Small change'] } })
  await expect.poll(async () => (await workspace.api(`/api/chats/${chat.id}`)).run?.status, { timeout: 20000 }).toBe('succeeded')
  const task = await workspace.api('/api/tasks', 'POST', { name: 'Claude scheduled work', prompt: 'Review the workspace', agentId: agent.id })
  const run = await workspace.api(`/api/tasks/${task.id}/run`, 'POST')
  await expect.poll(async () => (await workspace.api(`/api/runs/${run.id}`)).status, { timeout: 20000 }).toBe('succeeded')
  await page.goto('/connections')
  await section.getByRole('button', { name: 'Reconnect', exact: true }).click()
  await section.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(section.getByLabel('Claude authorization code')).toHaveCount(0)
})

test('switching coding agents preserves one chat, context and provider selection after reload', async ({ page, workspace }, testInfo) => {
  test.setTimeout(120000)
  await page.goto('/connections')
  await page.getByLabel('Password', { exact: true }).fill('browser-password-long-enough')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  const section = page.getByRole('region', { name: 'Claude Code', exact: true })
  await expect(section).toBeVisible()
  if (await section.getByRole('button', { name: 'Connect Claude Code', exact: true }).isVisible()) {
    await section.getByRole('button', { name: 'Connect Claude Code', exact: true }).click()
    await section.getByLabel('Claude authorization code').fill('fixture-code')
    await section.getByRole('button', { name: 'Finish sign-in' }).click()
  }
  await expect(section.getByText('Connected', { exact: true })).toBeVisible()
  const chat = await workspace.api('/api/chats', 'POST', {})
  await workspace.api(`/api/chats/${chat.id}/messages`, 'POST', { id: crypto.randomUUID(), text: 'Preserve the existing design. Work on this conversation.' })
  await expect.poll(async () => (await workspace.api(`/api/chats/${chat.id}`)).run?.status).toBe('succeeded')
  const first = await workspace.api(`/api/chats/${chat.id}`)
  await page.goto(`/chats/${chat.id}`)
  const picker = page.getByRole('button', { name: /^Agent, model and reasoning/ })
  const menu = page.getByRole('dialog', { name: 'Agent & model' })
  await picker.click()
  await expect(menu.getByRole('radio', { name: 'Codex', exact: true })).toHaveAttribute('aria-checked', 'true')
  await menu.getByRole('radio', { name: 'Claude Code', exact: true }).click()
  await expect(menu.getByText('The next message starts a new Claude Code session', { exact: false })).toBeVisible()
  // Claude's own "default" alias is the same choice as the provider default row.
  await expect(menu.getByRole('radio', { name: 'Default (recommended)', exact: true })).toHaveCount(0)
  await expect(menu.getByRole('radio', { name: 'Claude Code default', exact: true })).toHaveAccessibleDescription('Opus with 1M context · Best for everyday tasks')
  await menu.getByRole('radio', { name: 'Sonnet', exact: true }).click()
  await expect(menu.getByRole('radiogroup', { name: 'Reasoning' })).toBeVisible()
  await menu.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(menu).toHaveCount(0)
  for (const width of [1440, 390, 320]) {
    await page.setViewportSize({ width, height: width === 320 ? 600 : 900 })
    await expectSingleScroll(page)
    await expect(page.getByRole('button', { name: 'Send', exact: true })).toBeInViewport()
    await expect(picker).toBeInViewport()
    await page.screenshot({ path: testInfo.outputPath(`chat-provider-${width}.png`), animations: 'disabled' })
    await picker.click()
    await expect(menu.getByRole('radio', { name: 'Sonnet', exact: true })).toBeInViewport()
    const bounds = await menu.boundingBox()
    expect(bounds!.x).toBeGreaterThanOrEqual(0)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(width + 1)
    await page.screenshot({ path: testInfo.outputPath(`chat-provider-menu-${width}.png`), animations: 'disabled' })
    await page.keyboard.press('Escape')
    await expect(menu).toHaveCount(0)
  }
  await page.getByLabel('Message', { exact: true }).fill('Continue with Claude using the previous decisions.')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect.poll(async () => {
    const detail = await workspace.api(`/api/chats/${chat.id}`)
    return detail.run?.snapshot.agent.provider === 'claude' && detail.run.status === 'succeeded'
  }).toBe(true)
  const second = await workspace.api(`/api/chats/${chat.id}`)
  expect(second.runId).toBe(first.runId)
  expect(second.run.workspace).toBe(first.run.workspace)
  expect(second.run.chatExecution.context).toContain('Preserve the existing design')
  await page.reload()
  await expect(picker).toHaveAccessibleName(/^Agent, model and reasoning: Claude Code/)
  await picker.click()
  await expect(menu.getByRole('radio', { name: 'Claude Code', exact: true })).toHaveAttribute('aria-checked', 'true')
  await menu.getByRole('radio', { name: 'Codex', exact: true }).click()
  await page.keyboard.press('Escape')
  await page.getByLabel('Message', { exact: true }).fill('Return to Codex and keep the work.')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect.poll(async () => {
    const detail = await workspace.api(`/api/chats/${chat.id}`)
    return detail.run?.snapshot.agent.provider === 'codex' && detail.run.status === 'succeeded'
  }).toBe(true)
  const last = await workspace.api(`/api/chats/${chat.id}`)
  expect(last.runId).toBe(first.runId)
  expect(last.run.chatExecution.context).toContain('Claude fixture completed')
  expect(workspace.service.store.chatMessages(chat.id)).toHaveLength(3)
})
