import { expect, expectSingleScroll, initializeRepository, test } from './fixtures'

test('selects live models and supported reasoning for agents and queued chat turns', async ({ page, workspace }, testInfo) => {
  initializeRepository(workspace.projectPath)
  await page.goto('/')
  await page.getByLabel('Password', { exact: true }).fill('browser-password-long-enough')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.locator('.shell')).toBeVisible()
  await page.goto('/agents')
  await page.getByRole('button', { name: 'New agent', exact: true }).click()
  await page.getByLabel('Name', { exact: true }).fill('Model explorer')
  const picker = page.getByRole('button', { name: /^Agent, model and reasoning/ })
  const menu = page.getByRole('dialog', { name: 'Agent & model' })
  const reasoning = menu.getByRole('radiogroup', { name: 'Reasoning' })
  const effort = (name: string) => reasoning.getByRole('radio', { name, exact: true })
  await picker.click()
  await expect(menu.getByRole('radio', { name: 'Deep thinker', exact: true })).toBeVisible()
  await expect(menu.getByRole('radio', { name: 'Quick coder', exact: true })).toHaveCount(1)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: testInfo.outputPath('models-agent-desktop-light.png'), animations: 'disabled' })
  await menu.getByRole('radio', { name: 'Deep thinker', exact: true }).click()
  await expect(effort('High')).toHaveCount(0)
  await effort('Ultra').click()
  await menu.getByRole('radio', { name: 'Quick coder', exact: true }).click()
  await expect(effort('Model default · Low')).toHaveAttribute('aria-checked', 'true')
  await expect(effort('Ultra')).toHaveCount(0)
  await menu.getByRole('radio', { name: 'Deep thinker', exact: true }).click()
  await effort('Ultra').click()
  await menu.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(picker).toHaveAccessibleName('Agent, model and reasoning: Codex · Deep thinker · Ultra reasoning')
  await page.getByRole('button', { name: 'Save agent', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const agent = workspace.service.store.list('agents').find(agent => agent.name === 'Model explorer')!
  expect(agent.model).toBe('fixture-deep')
  expect(agent.reasoning).toBe('ultra')
  await page.locator('article').filter({ has: page.getByRole('button', { name: 'Model explorer', exact: true }) }).getByRole('link', { name: 'Start chat' }).click()
  await picker.click()
  await expect(effort('Agent default · Ultra')).toHaveAttribute('aria-checked', 'true')
  await menu.getByRole('radio', { name: 'Quick coder', exact: true }).click()
  await effort('High').click()
  await page.keyboard.press('Escape')
  await page.getByRole('textbox', { name: 'Message', exact: true }).fill('Review the layout. fixture:chat-hang')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page).toHaveURL(/\/chats\/[a-f0-9-]+$/)
  const chatId = page.url().split('/').at(-1)!
  await expect.poll(() => workspace.service.chats.detail(chatId).run?.status).toBe('running')
  expect(workspace.service.chats.detail(chatId).run?.snapshot.agent).toMatchObject({ model: 'fixture-fast', reasoning: 'high' })
  await picker.click()
  await menu.getByRole('radio', { name: 'Deep thinker', exact: true }).click()
  await effort('Ultra').click()
  await page.keyboard.press('Escape')
  await page.getByRole('textbox', { name: 'Message', exact: true }).fill('Investigate the keyboard shortcuts')
  await page.getByRole('button', { name: 'Queue', exact: true }).click()
  await page.getByRole('button', { name: 'Edit queued message' }).click()
  await expect(picker).toHaveAccessibleName(/Deep thinker · Ultra reasoning$/)
  await picker.click()
  await expect(effort('Ultra')).toHaveAttribute('aria-checked', 'true')
  await effort('Medium').click()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect.poll(() => workspace.service.chats.detail(chatId).messages.find(m => m.status === 'queued')).toMatchObject({ model: 'fixture-deep', reasoning: 'medium' })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(page.getByText('Agent saved', { exact: true })).not.toBeVisible()
  await expectSingleScroll(page)
  await picker.click()
  await expect(effort('Ultra')).toBeInViewport()
  await page.screenshot({ path: testInfo.outputPath('models-chat-mobile-dark.png'), animations: 'disabled' })
  await page.keyboard.press('Escape')
  await page.setViewportSize({ width: 320, height: 600 })
  await expectSingleScroll(page)
  await expect(page.getByRole('button', { name: 'Queue', exact: true })).toBeInViewport()
  await workspace.api(`/api/chats/${chatId}/messages`, 'POST', { id: crypto.randomUUID(), text: 'finish now', mode: 'steer' })
  await expect.poll(() => workspace.service.chats.detail(chatId).run?.summary).toContain('Investigate the keyboard shortcuts')
  expect(workspace.service.chats.detail(chatId).run?.snapshot.agent).toMatchObject({ model: 'fixture-deep', reasoning: 'medium' })
})
