import { randomUUID } from 'node:crypto'
import { expect, test } from './fixtures'

test('registers, configures and revokes a node through the owner interface', async ({ page, workspace }) => {
  test.setTimeout(60000)
  await page.goto('/')
  await page.getByLabel('Password', { exact: true }).fill('browser-password-long-enough')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.locator('.shell')).toBeVisible({ timeout: 30000 })
  await page.goto('/nodes')
  await page.getByLabel('Machine name').fill('Browser Linux')
  await page.getByRole('button', { name: 'Create enrollment code' }).click()
  const code = await page.locator('code').textContent()
  expect(code).toHaveLength(43)
  const response = await page.request.post(`${workspace.url}/internal/nodes/enroll`, { data: {
    code,
    name: 'Browser Linux',
    protocol: 1,
    runtimeId: 'fixture',
    capabilities: { os: 'linux', arch: 'x86_64', kvm: true, cpu: 8, memoryMiB: 16384, diskMiB: 65536 },
  } })
  expect(response.ok()).toBe(true)
  await page.reload()
  const node = page.getByRole('article').filter({ has: page.getByRole('heading', { name: 'Browser Linux' }) })
  await expect(node).toContainText('online')
  await node.getByRole('button', { name: 'Configure' }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('CPU ceiling').fill('4')
  await dialog.getByLabel('Tags, separated by commas').fill('fast, linux')
  await dialog.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(node).toContainText('4 CPU')
  await expect(node).toContainText('fast · linux')
  await page.getByRole('button', { name: 'Configure recovery points' }).click()
  await dialog.getByLabel('Capture interval (seconds)').fill('45')
  await dialog.getByLabel('Pause after disconnection (seconds)').fill('30')
  await dialog.getByLabel('Recovery points to retain').fill('4')
  await dialog.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  expect(await workspace.api('/api/nodes/settings')).toMatchObject({ intervalSeconds: 45, disconnectTimeoutSeconds: 30, retention: 4 })
  await node.getByRole('button', { name: 'Revoke', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Revoke node' }).click()
  await expect(node).toContainText('revoked')
  await expect(node.getByRole('button', { name: 'Configure' })).toHaveCount(0)
})

test('conversation placement distinguishes a preference from a strict pin and shows recovery age', async ({ page, workspace }) => {
  test.setTimeout(60000)
  const chat = await workspace.api('/api/chats', 'POST', {})
  await workspace.api(`/api/chats/${chat.id}/messages`, 'POST', { id: randomUUID(), text: 'Inspect the fixture' })
  await expect.poll(async () => (await workspace.api(`/api/chats/${chat.id}`)).run?.status, { timeout: 20000 }).toBe('succeeded')
  const detail = await workspace.api(`/api/chats/${chat.id}`)
  const invitation = await workspace.api('/api/nodes/enrollments', 'POST', { name: 'Recovery server' })
  const response = await page.request.post(`${workspace.url}/internal/nodes/enroll`, { data: { code: invitation.code, name: 'Recovery server', protocol: 1, runtimeId: 'fixture', capabilities: { os: 'linux', arch: 'x86_64', kvm: true, cpu: 8, memoryMiB: 16384, diskMiB: 65536 } } })
  expect(response.ok()).toBe(true)
  const node = await response.json()
  const agent = (await workspace.api('/api/agents')).find((agent: { id: string }) => agent.id === detail.run.snapshot.agent.id)
  await workspace.api(`/api/agents/${agent.id}`, 'PUT', { ...agent, access: { ...agent.access, nodes: [node.nodeId] } })
  workspace.service.store.updateRun(detail.run.id, { nodeId: node.nodeId, backup: { capturedAt: Date.now() - 120000, status: 'ready' } } as any)
  await page.goto(`/chats/${chat.id}`)
  await page.getByLabel('Password', { exact: true }).fill('browser-password-long-enough')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByText('Recoverable VM state:', { exact: false })).toBeVisible({ timeout: 30000 })
  await page.getByText('Execution node', { exact: true }).click()
  await page.getByLabel('Placement', { exact: true }).selectOption('preferred')
  await page.getByLabel('Node', { exact: true }).selectOption(node.nodeId)
  await page.getByRole('button', { name: 'Save placement' }).click()
  await expect.poll(async () => (await workspace.api(`/api/nodes/placement/${detail.run.id}`)).preferredNodeId).toBe(node.nodeId)
  await page.getByLabel('Placement', { exact: true }).selectOption('fixed')
  await page.getByRole('button', { name: 'Save placement' }).click()
  await expect.poll(async () => (await workspace.api(`/api/nodes/placement/${detail.run.id}`)).pinnedNodeId).toBe(node.nodeId)
  await expect(page.getByText('Fixed node; automatic failover disabled', { exact: false })).toBeVisible()
})
