import { expect, expectSingleScroll, test } from './fixtures'

test('1Password accounts keep tokens private and persist explicit agent grants', async ({ page, workspace }, testInfo) => {
  test.setTimeout(90000)
  await page.goto('/connections')
  await page.getByLabel('Password', { exact: true }).fill('browser-password-long-enough')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  const panel = page.getByRole('region', { name: '1Password accounts' })
  await panel.getByRole('button', { name: 'Add service account' }).click()
  let dialog = page.getByRole('dialog')
  await dialog.getByLabel('Name', { exact: true }).fill('Production secrets')
  const token = dialog.getByLabel('Service account token', { exact: true })
  await expect(token).toHaveAttribute('type', 'password')
  await token.fill('ops_browser_fixture')
  await expect(dialog.getByRole('checkbox', { name: 'Main agent', exact: true })).not.toBeChecked()
  await dialog.getByRole('checkbox', { name: 'Main agent', exact: true }).check()
  for (const width of [1440, 390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    await expectSingleScroll(page)
    await dialog.screenshot({ path: testInfo.outputPath(`onepassword-editor-${width}.png`) })
  }
  await dialog.getByRole('button', { name: 'Save account' }).click()
  await expect(dialog).toHaveCount(0)
  const accounts = await workspace.api('/api/onepassword')
  expect(accounts).toHaveLength(1)
  expect(JSON.stringify(accounts)).not.toContain('ops_browser_fixture')
  expect(accounts[0].agentIds).toHaveLength(1)
  await workspace.restart()
  await page.reload()
  await panel.getByRole('button', { name: 'Edit Production secrets', exact: true }).click()
  dialog = page.getByRole('dialog')
  await expect(dialog.getByLabel('Service account token', { exact: true })).toHaveValue('')
  await expect(dialog.getByRole('checkbox', { name: 'Main agent', exact: true })).toBeChecked()
  await dialog.getByRole('checkbox', { name: 'Main agent', exact: true }).uncheck()
  await dialog.getByRole('checkbox', { name: 'Enable this account' }).uncheck()
  await dialog.getByRole('button', { name: 'Save account' }).click()
  await expect(panel.getByText('Disabled · 0 authorized agents')).toBeVisible()
  const updated = await workspace.api('/api/onepassword')
  expect(updated[0].agentIds).toEqual([])
  expect(updated[0].enabled).toBe(false)
  await panel.getByRole('button', { name: 'Delete Production secrets', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Delete account', exact: true }).click()
  await expect(panel.getByText('No 1Password service accounts yet.')).toBeVisible()
})
