import { expect, test } from './fixtures'

const skill = (name: string, description: string) => `---\nname: ${name}\ndescription: ${description}\n---\nFollow the ${name} checklist.\n`

test('typing $ suggests skills, inserts one with the keyboard and invokes it for the agent', async ({ page, workspace }) => {
  test.setTimeout(90000)
  await workspace.api('/api/skills/global/review', 'PUT', { content: skill('review', 'Review the current changes before shipping') })
  await workspace.api('/api/skills/global/deploy-app', 'PUT', { content: skill('deploy-app', 'Publish a release') })
  const chat = await workspace.api('/api/chats', 'POST', {})
  await page.goto(`/chats/${chat.id}`)
  await page.getByLabel('Password', { exact: true }).fill('browser-password-long-enough')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  const composer = page.getByRole('textbox', { name: 'Message', exact: true })
  const menu = page.getByRole('listbox', { name: 'Skills', exact: true })
  await expect(composer).toHaveAttribute('placeholder', 'Message your agent… Type $ for skills')
  await composer.pressSequentially('Please $')
  await expect(menu).toBeVisible()
  await expect(menu.getByRole('option')).toHaveText([/\$deploy-app.*Publish a release/, /\$review.*Review the current changes/])
  await expect(menu.getByRole('option').first()).toHaveAttribute('aria-selected', 'true')
  await page.screenshot({ path: test.info().outputPath('skill-menu-desktop.png'), animations: 'disabled' })
  await page.keyboard.press('ArrowDown')
  await expect(menu.getByRole('option', { name: /review/ })).toHaveAttribute('aria-selected', 'true')
  await composer.pressSequentially('rev')
  await expect(menu.getByRole('option')).toHaveCount(1)
  await page.keyboard.press('Enter')
  await expect(menu).toHaveCount(0)
  await expect(composer).toHaveValue('Please $review ')
  await expect(page.locator('.skill-token')).toHaveText('$review')
  await page.locator('form.chat-composer').screenshot({ path: test.info().outputPath('skill-token-desktop.png'), animations: 'disabled' })
  // Escape dismisses the list without changing the draft; `$5` never opens it.
  await composer.pressSequentially('then $d')
  await expect(menu.getByRole('option')).toHaveText([/\$deploy-app/])
  await page.keyboard.press('Escape')
  await expect(menu).toHaveCount(0)
  await expect(composer).toHaveValue('Please $review then $d')
  await composer.press('Backspace')
  await composer.press('Backspace')
  await composer.pressSequentially('for $5')
  await expect(menu).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  await composer.fill('')
  await composer.pressSequentially('Mobile $de')
  await expect(menu).toBeVisible()
  const box = await menu.boundingBox()
  expect(box!.x).toBeGreaterThanOrEqual(0)
  expect(box!.x + box!.width).toBeLessThanOrEqual(390)
  await page.screenshot({ path: test.info().outputPath('skill-menu-mobile.png'), animations: 'disabled' })
  await menu.getByRole('option', { name: /deploy-app/ }).click()
  await expect(composer).toHaveValue('Mobile $deploy-app ')
  await expect(composer).toBeFocused()
  await composer.fill('Use $review on the workspace, not $HOME')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect.poll(async () => (await workspace.api(`/api/chats/${chat.id}`)).run?.status, { timeout: 20000 }).toBe('succeeded')
  const run = (await workspace.api(`/api/chats/${chat.id}`)).run
  expect(run.chatExecution.text).toContain('<invoked_skills>')
  expect(run.chatExecution.text).toContain('\n- review\n')
  expect(run.chatExecution.text).not.toContain('- HOME')
  const sent = page.locator('.activity-message').filter({ has: page.getByText('You', { exact: true }), hasText: 'Use $review on the workspace' })
  await expect(sent.getByTitle('Skill review')).toHaveText('$review')
  await sent.screenshot({ path: test.info().outputPath('skill-message-mobile.png'), animations: 'disabled' })
  await expect(sent).not.toContainText('invoked_skills')
})
