import { expect, expectSingleScroll, test } from './fixtures'

test('reconnects after a temporary restart and resumes a cancelled conversation in place', async ({ page, workspace }) => {
  const agent = workspace.service.agent({ name: 'Recovery engineer' })
  const project = workspace.service.store.list('projects')[0]
  const task = workspace.service.task({ name: 'Recover a deployment review', agentId: agent.id, projectId: project.id, prompt: 'fixture:restart', worktree: false })
  const run = await workspace.service.enqueue(task.id)
  await expect.poll(() => workspace.service.store.run(run.id)?.sessionId).toBe('fixture-session')
  await page.goto('/')
  await page.getByLabel('Password', { exact: true }).fill('browser-password-long-enough')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.locator('.task-focus-detail')).toBeVisible()
  let available = false
  await page.route(`**/api/runs/${run.id}`, async (route) => {
    if (available)
      await route.continue()
    else await route.fulfill({ status: 503, json: { error: 'Worker is restarting' } })
  })
  await page.goto(`/runs/${run.id}`)
  await expect(page.getByText('Worker is restarting', { exact: true })).toBeVisible()
  available = true
  await expect(page.getByRole('heading', { name: task.name })).toBeVisible()
  await expect(page.getByText('Worker is restarting', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Stop run', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Stop run', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Resume', exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(page.locator('.sidebar')).not.toBeInViewport()
  await expectSingleScroll(page)
  await page.screenshot({ animations: 'disabled', path: test.info().outputPath('resume-mobile-dark.png') })
  await expect(page.getByRole('button', { name: 'Resume', exact: true })).toBeInViewport()
  await page.getByRole('button', { name: 'Resume', exact: true }).click()
  await expect.poll(() => workspace.service.store.run(run.id)?.status).toBe('succeeded')
  await page.getByRole('button', { name: 'Result', exact: true }).click()
  await expect(page.getByText('The saved conversation and work survived the restart.', { exact: true })).toBeVisible()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.emulateMedia({ colorScheme: 'light' })
  await page.screenshot({ animations: 'disabled', path: test.info().outputPath('resumed-desktop-light.png') })
  expect(workspace.service.store.runs().filter(item => item.taskId === task.id)).toHaveLength(1)
})

test('keeps task selection across reloads and discards a previous run response', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Password', { exact: true }).fill('browser-password-long-enough')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.locator('.task-focus-detail')).toBeVisible()
  const session = await page.request.get('/api/session').then(response => response.json())
  const existing = await page.request.get('/api/tasks').then(response => response.json())
  const activity = await page.request.get('/api/tasks/activity').then(response => response.json())
  const created = await page.request.post('/api/tasks', { headers: { 'X-CSRF-Token': session.csrf }, data: { name: 'Fresh task without a run', prompt: 'This is the new task brief.', agentId: existing[0].agentId, enabled: false, worktree: false } })
  expect(created.ok()).toBe(true)
  const task = await created.json()
  let release!: () => void
  const gate = new Promise<void>(resolve => release = resolve)
  await page.route(`**/api/runs/${activity[0].id}/events?*`, async (route) => {
    await gate
    await route.fulfill({ json: [{ id: 9999, runId: activity[0].id, type: 'item.completed', createdAt: Date.now(), text: 'STALE RUN MESSAGE', payload: { item: { type: 'agent_message', text: 'STALE RUN MESSAGE' } } }] })
  })
  try {
    await page.goto(`/tasks?task=${existing[0].id}`)
    await expect(page.locator('.run-title-meta')).toBeVisible()
    await page.getByRole('button', { name: /Fresh task without a run/ }).click()
    await expect(page.locator('.task-focus-detail')).toContainText('This is the new task brief.')
    release()
    await expect(page.locator('.task-focus-detail')).not.toContainText('STALE RUN MESSAGE')
    await expect(page).toHaveURL(new RegExp(`task=${task.id}`))
    await page.reload()
    await expect(page.locator('.task-focus-detail')).toContainText('Fresh task without a run')
    await expect(page.locator('.task-focus-detail .activity-feed')).toHaveCount(0)
    await page.setViewportSize({ width: 390, height: 844 })
    await page.getByRole('button', { name: 'Choose task' }).click()
    await page.getByRole('button', { name: /Weekly dependency review/ }).click()
    await expect(page.locator('.task-inbox-row.selected')).toContainText('Weekly dependency review')
    await page.setViewportSize({ width: 390, height: 664 })
    await page.getByRole('button', { name: 'Run now', exact: true }).click()
    await page.getByRole('button', { name: 'Stop run', exact: true }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await page.getByRole('dialog').getByRole('button', { name: 'Stop run', exact: true }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
  }
  finally {
    release()
  }
})
