import { expect, expectSingleScroll, test } from './fixtures'

test('reconnects after a temporary restart and resumes a cancelled conversation in place', async ({ page, workspace }) => {
  const agent = workspace.service.agent({ name: 'Recovery engineer' })
  const project = workspace.service.store.list('projects')[0]
  const task = workspace.service.task({ name: 'Recover a deployment review', agentId: agent.id, projectId: project.id, prompt: 'fixture:restart', worktree: false })
  const run = await workspace.service.enqueue(task.id)
  await expect.poll(() => workspace.service.store.run(run.id)?.sessionId).toBe('fixture-session')
  await page.goto('/tasks')
  await page.getByLabel('Password', { exact: true }).fill('browser-password-long-enough')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.locator('.task-focus-detail')).toBeVisible()
  let available = false
  await page.route(`**/api/runs/${run.id}/stream?*`, async (route) => {
    if (available)
      await route.continue()
    else await route.fulfill({ status: 503, json: { error: 'Worker is restarting' } })
  })
  await page.goto(`/runs/${run.id}`)
  await expect(page.getByRole('status').filter({ hasText: 'Reconnecting' })).toBeVisible()
  available = true
  await expect(page.getByRole('heading', { name: task.name })).toBeVisible()
  await expect(page.getByRole('status').filter({ hasText: 'Reconnecting' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Stop run', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Stop run', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Resume', exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(page.getByRole('navigation', { name: 'Workspace navigation' })).toBeHidden()
  await expectSingleScroll(page)
  await page.screenshot({ animations: 'disabled', path: test.info().outputPath('resume-mobile-dark.png') })
  await expect(page.getByRole('button', { name: 'Resume', exact: true })).toBeInViewport()
  await page.getByRole('button', { name: 'Resume', exact: true }).click()
  await expect.poll(() => workspace.service.store.run(run.id)?.status).toBe('succeeded')
  await page.getByRole('button', { name: 'Result', exact: true }).click()
  await expect(page.getByText('The saved conversation and work survived the restart.', { exact: true })).toBeVisible()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.emulateMedia({ colorScheme: 'light' })
  await page.screenshot({ animations: 'disabled', path: test.info().outputPath('resumed-desktop-light.png') })
  expect(workspace.service.store.runs().filter(item => item.taskId === task.id)).toHaveLength(1)
})

test('keeps task selection across reloads and discards a previous run response', async ({ page }) => {
  await page.goto('/tasks')
  await page.getByLabel('Password', { exact: true }).fill('browser-password-long-enough')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.locator('.task-focus-detail')).toBeVisible()
  const session = await page.request.get('/api/session').then(response => response.json())
  const existing = await page.request.get('/api/tasks').then(response => response.json())
  const activity = await page.request.get('/api/tasks/activity').then(response => response.json())
  const created = await page.request.post('/api/tasks', { headers: { 'X-CSRF-Token': session.csrf }, data: { name: 'Fresh task without a run', prompt: 'This is the new task brief.', agentId: existing[0].agentId, enabled: false, worktree: false } })
  expect(created.ok()).toBe(true)
  const task = await created.json()
  let release!: () => void
  const gate = new Promise<void>(resolve => release = resolve)
  let requested = false
  await page.route(`**/api/runs/${activity[0].id}/stream?*`, async (route) => {
    requested = true
    await gate
    const batch = { reset: false, more: false, events: [{ id: 9999, runId: activity[0].id, type: 'item.completed', createdAt: Date.now(), text: 'STALE RUN MESSAGE', payload: { item: { type: 'agent_message', text: 'STALE RUN MESSAGE' } } }] }
    await route.fulfill({ contentType: 'text/event-stream', body: `event: batch\nid: 9999\ndata: ${JSON.stringify(batch)}\n\n` })
  })
  try {
    await page.goto(`/tasks?task=${existing[0].id}`)
    await expect.poll(() => requested).toBe(true)
    await page.getByRole('button', { name: /Fresh task without a run/ }).click()
    await expect(page.locator('.task-focus-detail')).toContainText('This is the new task brief.')
    release()
    await expect(page.locator('.task-focus-detail')).not.toContainText('STALE RUN MESSAGE')
    await expect(page).toHaveURL(new RegExp(`task=${task.id}`))
    await page.reload()
    await expect(page.locator('.task-focus-detail')).toContainText('Fresh task without a run')
    await expect(page.locator('.task-focus-detail .activity-feed')).toHaveCount(0)
    await page.setViewportSize({ width: 390, height: 844 })
    await page.getByRole('button', { name: 'Choose mission' }).click()
    await page.getByRole('button', { name: /Weekly dependency review/ }).click()
    await expect(page.locator('.task-inbox-row.selected')).toContainText('Weekly dependency review')
    await page.setViewportSize({ width: 390, height: 664 })
    await page.getByLabel('Mission actions', { exact: true }).click()
    await page.getByRole('button', { name: 'Run now', exact: true }).click()
    await page.getByRole('button', { name: 'Stop run', exact: true }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await page.getByRole('dialog').getByRole('button', { name: 'Stop run', exact: true }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
  }
  finally {
    release()
  }
})

test('compact task workspace keeps the conversation visible and details reachable', async ({ page, workspace }) => {
  await workspace.restart()
  const agent = workspace.service.store.list('agents')[0]
  const project = workspace.service.store.list('projects')[0]
  const task = workspace.service.task({ name: 'Weekly Graphile Worker upstream ports', agentId: agent.id, projectId: project.id, prompt: 'Review upstream changes and report the checks you ran. fixture:activity', cron: '0 9 * * 4', enabled: false, worktree: false })
  const run = await workspace.service.enqueue(task.id)
  await expect.poll(() => workspace.service.store.run(run.id)?.status).toBe('succeeded')
  const reply = '## The upstream review is complete.\n\nThe applicable changes have been integrated. No identified change remains pending.\n\n- **Tests passed** for the updated functionality.\n- PostgreSQL compatibility checked.\n- SQL scenarios and API comparisons reviewed.\n\nThe audit report records the decision for each upstream change.'
  workspace.service.store.event(run.id, 'item.completed', reply, { item: { type: 'agent_message', text: reply } })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.goto(`/tasks?task=${task.id}`)
  await page.getByLabel('Password', { exact: true }).fill('browser-password-long-enough')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: task.name, exact: true })).toHaveCount(1)
  await expect(page.getByRole('region', { name: 'Activity output' })).toBeVisible()
  const bounds = await page.getByRole('region', { name: 'Activity output' }).boundingBox()
  expect(bounds!.height).toBeGreaterThan(500)
  expect(bounds!.y).toBeLessThan(210)
  await expectSingleScroll(page)
  await expect(page.getByRole('button', { name: 'Choose mission' })).toBeVisible()
  await page.getByRole('button', { name: 'Details', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Mission details' })).toContainText('0 9 * * 4')
  await expect(page.getByRole('dialog')).toContainText(task.prompt)
  await page.getByRole('button', { name: 'Execution details', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Execution details' })).toContainText('Original instructions')
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.getByRole('button', { name: 'Open activity fullscreen', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Fullscreen activity' })).toBeVisible()
  await page.getByRole('button', { name: 'Exit fullscreen', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Open activity fullscreen', exact: true })).toBeFocused()
  await page.getByRole('group', { name: 'Run view' }).getByRole('button', { name: /^Files/ }).click()
  await expect(page.getByText('No files published yet.')).toBeVisible()
  await page.getByRole('button', { name: 'Result', exact: true }).click()
  await expect(page.locator('.result-content')).toBeVisible()
  await page.getByRole('button', { name: 'Conversation', exact: true }).click()
  await page.getByRole('button', { name: 'Choose mission' }).click()
  await page.getByRole('textbox', { name: 'Search missions' }).fill('no matching task')
  await expect(page.getByRole('heading', { name: 'No matching missions' })).toBeVisible()
  await page.getByRole('textbox', { name: 'Search missions' }).fill('Graphile')
  await page.getByRole('button', { name: new RegExp(task.name) }).click()
  await expect(page.getByRole('button', { name: 'Choose mission' })).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByRole('region', { name: 'Activity output' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'The upstream review is complete.' })).toBeVisible()
  for (const group of await page.locator('.activity-group-toggle[aria-expanded="true"]').all())
    await group.click()
  await page.getByRole('region', { name: 'Activity output' }).evaluate(element => element.scrollTop = element.scrollHeight)
  await expect(page.getByRole('heading', { name: 'The upstream review is complete.' })).toBeVisible()
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ animations: 'disabled', path: test.info().outputPath('tasks-a-mobile.png') })
  await page.setViewportSize({ width: 1440, height: 960 })
  await expect(page.getByRole('textbox', { name: 'Search missions' })).toBeVisible()
  await page.getByRole('textbox', { name: 'Search missions' }).fill('')
  await expect(page.getByRole('button', { name: /Weekly dependency review/ })).toBeVisible()
  await page.locator('.task-title').click()
  await expectSingleScroll(page)
  await page.screenshot({ animations: 'disabled', path: test.info().outputPath('tasks-a-desktop.png') })
  for (const status of ['needs_input', 'blocked'] as const) {
    workspace.service.store.updateRun(run.id, { outcome: { status, reason: 'Review the upstream API change before continuing.', evidence: [], reportedAt: Date.now() } })
    await page.reload()
    await page.getByRole('button', { name: status === 'needs_input' ? 'Your input needed' : 'Blocked', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: 'Mission details' })
    await dialog.locator('summary').click()
    await expect(dialog).toContainText('Review the upstream API change before continuing.')
    await page.getByRole('button', { name: 'Close dialog' }).click()
  }
  await workspace.restart()
})
